# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vampire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='accepted_by',
            field=models.NullBooleanField(),
        ),
    ]
