# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vampire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='aid',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='aid',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='did',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='hid',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='aid',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='aid',
            new_name='address',
        ),
    ]
