# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vampire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='mobile_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[(0, 'select'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default=0, max_length=100),
        ),
    ]
