# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vampire', '0002_auto_20160423_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vampire.Donor'),
        ),
    ]
