# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vampire', '0003_auto_20160420_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
